//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Stolovka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Блюдо.
    /// </summary>
    //  *** Start programmer edit section *** (Блюдо CustomAttributes)

    //  *** End programmer edit section *** (Блюдо CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БлюдоE", new string[] {
            "Название as \'Название\'",
            "Стоимость as \'Стоимость\'",
            "ТипБлюда as \'Тип блюда\'",
            "ТипБлюда.Название as \'Название\'"}, Hidden=new string[] {
            "ТипБлюда.Название"})]
    [MasterViewDefineAttribute("БлюдоE", "ТипБлюда", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class Блюдо : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private double fСтоимость;
        
        private IIS.Stolovka.ТипБлюда fТипБлюда;
        
        private IIS.Stolovka.Заказ fЗаказ;
        
        //  *** Start programmer edit section *** (Блюдо CustomMembers)

        //  *** End programmer edit section *** (Блюдо CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        //  *** Start programmer edit section *** (Блюдо.Название CustomAttributes)

        //  *** End programmer edit section *** (Блюдо.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                //  *** Start programmer edit section *** (Блюдо.Название Get start)

                //  *** End programmer edit section *** (Блюдо.Название Get start)
                string result = this.fНазвание;
                //  *** Start programmer edit section *** (Блюдо.Название Get end)

                //  *** End programmer edit section *** (Блюдо.Название Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Блюдо.Название Set start)

                //  *** End programmer edit section *** (Блюдо.Название Set start)
                this.fНазвание = value;
                //  *** Start programmer edit section *** (Блюдо.Название Set end)

                //  *** End programmer edit section *** (Блюдо.Название Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        //  *** Start programmer edit section *** (Блюдо.Стоимость CustomAttributes)

        //  *** End programmer edit section *** (Блюдо.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                //  *** Start programmer edit section *** (Блюдо.Стоимость Get start)

                //  *** End programmer edit section *** (Блюдо.Стоимость Get start)
                double result = this.fСтоимость;
                //  *** Start programmer edit section *** (Блюдо.Стоимость Get end)

                //  *** End programmer edit section *** (Блюдо.Стоимость Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Блюдо.Стоимость Set start)

                //  *** End programmer edit section *** (Блюдо.Стоимость Set start)
                this.fСтоимость = value;
                //  *** Start programmer edit section *** (Блюдо.Стоимость Set end)

                //  *** End programmer edit section *** (Блюдо.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Блюдо.
        /// </summary>
        //  *** Start programmer edit section *** (Блюдо.ТипБлюда CustomAttributes)

        //  *** End programmer edit section *** (Блюдо.ТипБлюда CustomAttributes)
        [NotNull()]
        public virtual IIS.Stolovka.ТипБлюда ТипБлюда
        {
            get
            {
                //  *** Start programmer edit section *** (Блюдо.ТипБлюда Get start)

                //  *** End programmer edit section *** (Блюдо.ТипБлюда Get start)
                IIS.Stolovka.ТипБлюда result = this.fТипБлюда;
                //  *** Start programmer edit section *** (Блюдо.ТипБлюда Get end)

                //  *** End programmer edit section *** (Блюдо.ТипБлюда Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Блюдо.ТипБлюда Set start)

                //  *** End programmer edit section *** (Блюдо.ТипБлюда Set start)
                this.fТипБлюда = value;
                //  *** Start programmer edit section *** (Блюдо.ТипБлюда Set end)

                //  *** End programmer edit section *** (Блюдо.ТипБлюда Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Stolovka.Заказ.
        /// </summary>
        //  *** Start programmer edit section *** (Блюдо.Заказ CustomAttributes)

        //  *** End programmer edit section *** (Блюдо.Заказ CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Stolovka.Заказ Заказ
        {
            get
            {
                //  *** Start programmer edit section *** (Блюдо.Заказ Get start)

                //  *** End programmer edit section *** (Блюдо.Заказ Get start)
                IIS.Stolovka.Заказ result = this.fЗаказ;
                //  *** Start programmer edit section *** (Блюдо.Заказ Get end)

                //  *** End programmer edit section *** (Блюдо.Заказ Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Блюдо.Заказ Set start)

                //  *** End programmer edit section *** (Блюдо.Заказ Set start)
                this.fЗаказ = value;
                //  *** Start programmer edit section *** (Блюдо.Заказ Set end)

                //  *** End programmer edit section *** (Блюдо.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БлюдоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БлюдоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БлюдоE", typeof(IIS.Stolovka.Блюдо));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Блюдо.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfБлюдо CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfБлюдо CustomAttributes)
    public class DetailArrayOfБлюдо : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Stolovka.DetailArrayOfБлюдо members)

        //  *** End programmer edit section *** (IIS.Stolovka.DetailArrayOfБлюдо members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Блюдо by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Блюдо.
        /// </summary>
        public DetailArrayOfБлюдо(IIS.Stolovka.Заказ fЗаказ) : 
                base(typeof(Блюдо), ((ICSSoft.STORMNET.DataObject)(fЗаказ)))
        {
        }
        
        public IIS.Stolovka.Блюдо this[int index]
        {
            get
            {
                return ((IIS.Stolovka.Блюдо)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Stolovka.Блюдо dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
