//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Stolovka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказчик.
    /// </summary>
    //  *** Start programmer edit section *** (Заказчик CustomAttributes)

    //  *** End programmer edit section *** (Заказчик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказчикE", new string[] {
            "Название as \'Название\'"})]
    [View("ЗаказчикL", new string[] {
            "Название as \'Название\'"})]
    public class Заказчик : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        //  *** Start programmer edit section *** (Заказчик CustomMembers)

        //  *** End programmer edit section *** (Заказчик CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        //  *** Start programmer edit section *** (Заказчик.Название CustomAttributes)

        //  *** End programmer edit section *** (Заказчик.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                //  *** Start programmer edit section *** (Заказчик.Название Get start)

                //  *** End programmer edit section *** (Заказчик.Название Get start)
                string result = this.fНазвание;
                //  *** Start programmer edit section *** (Заказчик.Название Get end)

                //  *** End programmer edit section *** (Заказчик.Название Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Заказчик.Название Set start)

                //  *** End programmer edit section *** (Заказчик.Название Set start)
                this.fНазвание = value;
                //  *** Start programmer edit section *** (Заказчик.Название Set end)

                //  *** End programmer edit section *** (Заказчик.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказчикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказчикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказчикE", typeof(IIS.Stolovka.Заказчик));
                }
            }
            
            /// <summary>
            /// "ЗаказчикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказчикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказчикL", typeof(IIS.Stolovka.Заказчик));
                }
            }
        }
    }
}
