//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Stolovka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    //  *** Start programmer edit section *** (Заказ CustomAttributes)

    //  *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "Дата as \'Дата\'",
            "Итог as \'Итог\'",
            "Заказчик as \'Заказчик\'",
            "Заказчик.Название as \'Название\'"})]
    [AssociatedDetailViewAttribute("ЗаказE", "Блюдо", "БлюдоE", true, "", "Блюдо", true, new string[] {
            ""})]
    [View("ЗаказL", new string[] {
            "Дата as \'Дата\'",
            "Итог as \'Итог\'",
            "Заказчик.Название as \'Название\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private double fИтог;
        
        private IIS.Stolovka.Заказчик fЗаказчик;
        
        private IIS.Stolovka.DetailArrayOfБлюдо fБлюдо;
        
        //  *** Start programmer edit section *** (Заказ CustomMembers)

        //  *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        //  *** Start programmer edit section *** (Заказ.Дата CustomAttributes)

        //  *** End programmer edit section *** (Заказ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                //  *** Start programmer edit section *** (Заказ.Дата Get start)

                //  *** End programmer edit section *** (Заказ.Дата Get start)
                System.DateTime result = this.fДата;
                //  *** Start programmer edit section *** (Заказ.Дата Get end)

                //  *** End programmer edit section *** (Заказ.Дата Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Заказ.Дата Set start)

                //  *** End programmer edit section *** (Заказ.Дата Set start)
                this.fДата = value;
                //  *** Start programmer edit section *** (Заказ.Дата Set end)

                //  *** End programmer edit section *** (Заказ.Дата Set end)
            }
        }
        
        /// <summary>
        /// Итог.
        /// </summary>
        //  *** Start programmer edit section *** (Заказ.Итог CustomAttributes)

        //  *** End programmer edit section *** (Заказ.Итог CustomAttributes)
        public virtual double Итог
        {
            get
            {
                //  *** Start programmer edit section *** (Заказ.Итог Get start)

                //  *** End programmer edit section *** (Заказ.Итог Get start)
                double result = this.fИтог;
                //  *** Start programmer edit section *** (Заказ.Итог Get end)

                //  *** End programmer edit section *** (Заказ.Итог Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Заказ.Итог Set start)

                //  *** End programmer edit section *** (Заказ.Итог Set start)
                this.fИтог = value;
                //  *** Start programmer edit section *** (Заказ.Итог Set end)

                //  *** End programmer edit section *** (Заказ.Итог Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        //  *** Start programmer edit section *** (Заказ.Заказчик CustomAttributes)

        //  *** End programmer edit section *** (Заказ.Заказчик CustomAttributes)
        public virtual IIS.Stolovka.Заказчик Заказчик
        {
            get
            {
                //  *** Start programmer edit section *** (Заказ.Заказчик Get start)

                //  *** End programmer edit section *** (Заказ.Заказчик Get start)
                IIS.Stolovka.Заказчик result = this.fЗаказчик;
                //  *** Start programmer edit section *** (Заказ.Заказчик Get end)

                //  *** End programmer edit section *** (Заказ.Заказчик Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Заказ.Заказчик Set start)

                //  *** End programmer edit section *** (Заказ.Заказчик Set start)
                this.fЗаказчик = value;
                //  *** Start programmer edit section *** (Заказ.Заказчик Set end)

                //  *** End programmer edit section *** (Заказ.Заказчик Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        //  *** Start programmer edit section *** (Заказ.Блюдо CustomAttributes)

        //  *** End programmer edit section *** (Заказ.Блюдо CustomAttributes)
        public virtual IIS.Stolovka.DetailArrayOfБлюдо Блюдо
        {
            get
            {
                //  *** Start programmer edit section *** (Заказ.Блюдо Get start)

                //  *** End programmer edit section *** (Заказ.Блюдо Get start)
                if ((this.fБлюдо == null))
                {
                    this.fБлюдо = new IIS.Stolovka.DetailArrayOfБлюдо(this);
                }
                IIS.Stolovka.DetailArrayOfБлюдо result = this.fБлюдо;
                //  *** Start programmer edit section *** (Заказ.Блюдо Get end)

                //  *** End programmer edit section *** (Заказ.Блюдо Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Заказ.Блюдо Set start)

                //  *** End programmer edit section *** (Заказ.Блюдо Set start)
                this.fБлюдо = value;
                //  *** Start programmer edit section *** (Заказ.Блюдо Set end)

                //  *** End programmer edit section *** (Заказ.Блюдо Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Stolovka.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Stolovka.Заказ));
                }
            }
        }
    }
}
